trigger:
  branches:
    include:
    - main
    - feature/*
    - fix/*
    - bug/*
    - test/*

  paths:
    include:
    - code
    exclude:
    - .attachments
    - infrastructure
    - yaml

variables:
- name: files.path
  value: code
- name: app_name
  value: 'oncall-alarm'

stages:

- stage: Test
  displayName: 'Deploy Test'
  condition: and(always(), ne(variables['Build.SourceBranch'], 'refs/heads/main'))
  dependsOn: []
  variables:
  - group: 'infra_sandbox'
  - name: 'environment'
    value: 'infra-sandbox-test'
  - name: 'bucket'
    value: 'wdrx-sandbox-deployments'
  jobs:

  - deployment: deployTest
    displayName: Deploy Test
    pool:
      vmImage: 'ubuntu-latest'

    environment: 'test-infra-sandbox-$(app_name)-app-code'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - template: templates/code-cd.yml
            parameters:
              hclServiceConnection: tf_infra_sandbox
              cspServiceConnection: aws_infra_sandbox

- stage: Prod
  displayName: 'Deploy Prod'
  condition: and(always(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  dependsOn: []
  variables:
  - group: 'infra_sandbox'
  - name: 'environment'
    value: 'infra-sandbox'
  - name: 'bucket'
    value: 'wdrx-sandbox-deployments'
  jobs:

  - job: prodApproval
    displayName: Wait for Manual Approval
    pool: server
    timeoutInMinutes: 43800
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 43800 # task times out in 1 month
        inputs:
           notifyUsers: |
             kmartinez@welldynerx.com
           instructions: 'Please validate the build configuration and resume'
           onTimeout: 'resume'

  - deployment: deployProd
    displayName: Deploy Prod
    dependsOn: prodApproval
    pool:
      vmImage: 'ubuntu-latest'

    environment: 'infra-sandbox-$(app_name)-app-code'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - template: templates/code-cd.yml
            parameters:
              hclServiceConnection: tf_infra_sandbox
              cspServiceConnection: aws_infra_sandbox