trigger:
  branches:
    include:
    - main
    - feature/*
    - fix/*
    - bug/*
    - test/*

  paths:
    include:
    - infrastructure
    exclude:
    - .attachments
    - code
    - yaml

variables:
- name: files.path
  value: infrastructure
- name: app_name
  value: 'oncall-alarm'
- name: 'tf.path'
  value: 'infrastructure'

stages:

- stage: Test
  displayName: 'Deploy Test'
  condition: and(always(), ne(variables['Build.SourceBranch'], 'refs/heads/main'))
  dependsOn: []
  variables:
  - group: 'oncall-alarm-grp-test'
  - group: 'infra_sandbox'
  - name: 'environment'
    value: 'infra-sandbox-test'
  jobs:

  - deployment: deployTest
    displayName: Deploy Test
    pool:
      vmImage: 'ubuntu-latest'

    environment: 'test-infra-sandbox-$(app_name)'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - template: templates/infrastructure-cd.yml
            parameters:
              hclServiceConnection: tf_infra_sandbox
              cspServiceConnection: aws_infra_sandbox

  - job: testDestructionApproval
    displayName: Approve Test Destruction
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/main'))
    dependsOn: ['deployTest']
    pool: server
    timeoutInMinutes: 43800
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 43800 # task times out in 1 month
        inputs:
           notifyUsers: |
             kmartinez@welldynerx.com
           instructions: 'Please confirm Oncall Alarm Test environment destruction.'
           onTimeout: 'resume'

  - deployment: destroyTest
    displayName: Destroy Test
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/main'))
    dependsOn: ['testDestructionApproval', 'deployTest']
    pool:
      vmImage: 'ubuntu-latest'

    environment: 'test-infra-sandbox-$(app_name)'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - template: templates/destroy-infrastructure.yml
            parameters:
              hclServiceConnection: tf_infra_sandbox
              cspServiceConnection: aws_infra_sandbox

- stage: Prod
  displayName: 'Deploy Prod'
  condition: and(always(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  dependsOn: []
  variables:
  - group: 'oncall-alarm-grp'
  - group: 'infra_sandbox'
  - name: 'environment'
    value: 'infra-sandbox'
  jobs:

  - job: prodApproval
    displayName: Wait for Manual Approval
    pool: server
    timeoutInMinutes: 43800
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 43800 # task times out in 1 month
        inputs:
           notifyUsers: |
             kmartinez@welldynerx.com
           instructions: 'Please validate the build configuration and resume'
           onTimeout: 'resume'

  - deployment: deployProd
    displayName: Deploy Prod
    dependsOn: prodApproval
    pool:
      vmImage: 'ubuntu-latest'

    environment: 'infra-sandbox-$(app_name)'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - template: templates/infrastructure-cd.yml
            parameters:
              hclServiceConnection: tf_infra_sandbox
              cspServiceConnection: aws_infra_sandbox